---
- hosts: '{{ hosts }}'
  gather_facts: no
  serial: 1
  roles:
  - apigee-opdk-setup-validate
  tags:
  - validate

- hosts: '{{ hosts }}'
  gather_facts: no
  serial: 1
  roles:
  - apigee-opdk-setup-validate-cleanup
  tags:
  - validate-cleanup
