---
- hosts: '{{ hosts }}'
  become: true
  strategy: free
  roles:
  - { role: apigee-fetch-files, fetch_files: '{{ system_config_files }}', fetched_files_dir: '{{ fetched_configs_dir }}/{{ hosts }}/' }
  tags:
  - logs
  - os-logs

- hosts: '{{ hosts }}'
  become: true
  strategy: free
  roles:
  - apigee-opdk-setup-default-settings
  tags:
  - logs
  - apigee-logs

- hosts: '{{ hosts }}'
  become: true
  strategy: free
  roles:
  - apigee-opdk-setup-default-settings
  tags:
  - logs
  - config-logs
