---
- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-enable-swap
  - apigee-opdk-setup-default-settings
  - apigee-opdk-setup-apigee-user
  - apigee-opdk-setup-os-postgres
  - apigee-opdk-setup-postgres-config

- include: opdk-install-component.yml
  vars:
    hosts: '{{ hosts }}'
    component_profile: 'ps'

- include: 'opdk-setup-postgres-{{ pg_component }}.yml'
  when: pg_component is defined

- hosts: '{{ hosts }}'
  serial: 1
  roles:
  - apigee-opdk-setup-default-settings
  - { role: apigee-opdk-server-self, server_type: 'ps'}
