---
- hosts: '{{ hosts }}'
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-enable-swap
  - apigee-opdk-setup-apigee-user
  - apigee-opdk-setup-os-postgres
  - apigee-opdk-setup-postgres-config

- include: opdk-install-component.yml
  vars:
    hosts: '{{ hosts }}'
    component_profile: 'ps'

- include: 'opdk-setup-postgres-master.yml'
  when: pg_component is defined and pg_component == 'master'
  tags:
  - apigee-component

- include: 'opdk-setup-postgres-standby.yml'
  when: pg_component is defined and pg_component == 'standby'
  tags:
  - apigee-component

- hosts: '{{ hosts }}'
  serial: 1
  roles:
  - { role: apigee-opdk-server-self, server_types: ['ps'] }
