---
- name: Update full cache
  hosts: planet
  gather_facts: no
  vars_files:
  - ~/.apigee/credentials.yml
  pre_tasks:
  - setup:

  - ec2_facts:
    when: "{{ ansible_bios_version | lower | search('amazon') }}"

  roles:
  - apigee-opdk-setup-default-settings

